trigger:
- master

pool:
  vmImage: 'windows-latest'

stages:
- stage: BuildRun
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build FirstJob
    - bash: echo $(PipelineLevelVariable)
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(Build.BuildId)
    - bash: echo $(Build.SourceBranchName)
    - bash: echo $(Build.SourcesDirectory)
    - bash: echo $(System.DefaultWorkingDirectory)
    - bash: ls -R $(System.DefaultWorkingDirectory)
    - bash: echo $(Build.ArtifactStagingDirectory)
    - bash: java -version
    - bash: node --version
    - bash: python --version 
    - bash: mvn -version
    - bash: docker --version
    - bash: docker-compose --version
  - job: PullLatestImageJob
    steps:
    - bash: docker pull akbarchandani/selenium-docker
  - job: StartGridJob
    dependsOn: PullLatestImageJob
    steps:
    - bash: docker-compose up -d hub chrome firefox
  - job: RunTestJob
    dependsOn: StartGridJob
    steps:
    - bash: docker-compose up search-module book-flight-module
  - job: PostJob
    dependsOn: RunTestJob
    steps:
    - bash: docker-compose down